### ISSUE TITLE
new tag type Tag_Long_Array

### ISSUE THREAD

**Issue by pca006132** [minecraft-dotnet/Substrate#42]
Although the specification is not here, according to MCP 1.12 pre 1, there is a new tag called the "Tag_Long_Array". The payload is similar to Tag_Byte_Array and Tag_Int_Array. The id of it is 12.

Minecraft can currently add this tag although it is not used anywhere (Players can give an item with that tag through something like `give @p diamond_sword 1 0 {foo:[L;123l]}`, and that would cause the software to malfunction.). So update is required for this tag.

**Comment by jaquadro** [comment]
I wondered if this would ever come along.

**Comment by pca006132** [comment]
I've test it in 1.12 release, it works. (The whole player data can't be viewed by NBTExplorer when there is an item with that tag)

**Comment by Pokechu22** [comment]
As of snapshot 17w47a, this tag is used in the chunk format.  Such an update is now needed for vanilla use.

**Comment by jaquadro** [comment]
thanks for letting me know about usage
