### ISSUE TITLE
Question: Do we still need to support .net 2.0?

### ISSUE THREAD

**Issue by redwyre** [minecraft-dotnet/Substrate#51]
I know you use it @jaquadro in NBTExplorer, is there a reason you're not using .net 4?

I think porting to .net core is probably a good idea too but I expect it would have the same limitations.

**Comment by jaquadro** [comment]
I don't think there's much reason to.  NBTE can retarget 4 the next time it needs an update from Substrate.  I'm less versed on core but isn't it more of a cross-compatible subset of 4.x?

**Comment by redwyre** [comment]
retargeted on .net standard instead
